#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend/
(exec < /dev/tty && node_modules/.bin/cz --hook) || true < /dev/null
# exec < /dev/tty && git cz --hook || true
# exec < /dev/tty && node_modules/.bin/cz --hook || true
